<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\BotForge.Core\BotForge.Core.csproj"/>
        <ProjectReference Include="..\..\src\BotForge.Routing\BotForge.Routing.csproj"/>
        <ProjectReference Include="..\..\src\BotForge.Routing.Abstractions\BotForge.Routing.Abstractions.csproj"/>
        <ProjectReference Include="..\BotForge.TestUtilities\BotForge.TestUtilities.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="coverlet.collector"/>
    </ItemGroup>

</Project>
