<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Rate-limiting contracts for TeleForge.</Description>
        <PackageTags>telegram;telegram-bot;bot;rate-limiting;abstractions</PackageTags>
    </PropertyGroup>
    <PropertyGroup>
        <RootNamespace>TeleForge.RateLimiting.Abstractions</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\TeleForge.Core\TeleForge.Core.csproj"/>
    </ItemGroup>
</Project>
