<Project>

    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))"/>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup Condition="'$(UsingMicrosoftNETSdkWeb)' != 'true'">
        <Content Include="appsettings.json" Condition="Exists('appsettings.json')">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="appsettings.*.json" Condition="Exists('appsettings.Development.json')" Exclude="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
