<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\TeleForge.Core\TeleForge.Core.csproj"/>
        <ProjectReference Include="..\..\src\TeleForge.Routing\TeleForge.Routing.csproj"/>
        <ProjectReference Include="..\..\src\TeleForge.Routing.Abstractions\TeleForge.Routing.Abstractions.csproj"/>
        <ProjectReference Include="..\TeleForge.TestUtilities\TeleForge.TestUtilities.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="coverlet.collector"/>
    </ItemGroup>

</Project>
