<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\TeleForge.Streaming\TeleForge.Streaming.csproj"/>
        <ProjectReference Include="..\..\src\TeleForge.Messaging\TeleForge.Messaging.csproj"/>
        <ProjectReference Include="..\..\src\TeleForge.Routing\TeleForge.Routing.csproj"/>
        <ProjectReference Include="..\..\src\TeleForge.Consumer\TeleForge.Consumer.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting"/>
    </ItemGroup>
</Project>
