<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\BotForge.Messaging\BotForge.Messaging.csproj"/>
        <ProjectReference Include="..\..\src\BotForge.Routing\BotForge.Routing.csproj"/>
        <ProjectReference Include="..\..\src\BotForge.Consumer\BotForge.Consumer.csproj"/>
        <ProjectReference Include="..\..\src\BotForge.Messaging.MassTransit\BotForge.Messaging.MassTransit.csproj"/>
        <ProjectReference Include="..\..\src\BotForge.RateLimiting.Redis\BotForge.RateLimiting.Redis.csproj"/>
        <ProjectReference Include="..\..\src\BotForge.Observability\BotForge.Observability.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting"/>
        <PackageReference Include="MassTransit.RabbitMQ"/>
        <PackageReference Include="StackExchange.Redis"/>
    </ItemGroup>
</Project>
